[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Production environment variables
[context.production.environment]
  VITE_API_URL = "https://test-honey.onrender.com"
  VITE_CLIENT_URL = "https://testhoneye.netlify.app/"

# Branch deploy environment variables - useful for staging/testing
[context.branch-deploy.environment]
  VITE_API_URL = "hhttps://test-honey.onrender.com"
  VITE_CLIENT_URL = "https://testhoneye.netlify.app/"
